language: cpp

os:
  - linux

install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -y
  - sudo apt-get install cmake -y

script:
  - python build_test.py

branches:
  only:
    - master
