name: android-arm
on:
  push:
    branches: [ test ]
jobs:
  android-armv7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S examples -B build -P arcbuild.cmake -DROOT=$ANDROID_HOME/ndk-bundle -DPLATFORM=android -DARCH=armv7-a
    - name: build
      run: cmake --build build -j2

  android-armv8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S examples -B build -P arcbuild.cmake -DROOT=$ANDROID_HOME/ndk-bundle -DPLATFORM=android -DARCH=armv8-a
    - name: build
      run: cmake --build build -j2
