name: ios-iphone
on: [push, pull_request]
jobs:
  ios-iphone-os:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S examples -B build -P arcbuild.cmake -DPLATFORM=ios -DARCH="armv7;armv7s;arm64;arm64e"
    - name: build
      run: cmake --build build -j2

  ios-iphone-simulator:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -S examples -B build -P arcbuild.cmake -DPLATFORM=ios -DARCH="i386;x86_64"
    - name: build
      run: cmake --build build -j2

