name: linux-x64-clang
on: [push, pull_request]
jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: configure
      env:
        CC: clang
        CXX: clang++
      run: mkdir build && cd build && cmake -P ../arcbuild.cmake -DPLATFORM=linux64 -DARCH=x86 ..
    - name: build
      run: cmake --build build -j2
