name: linux-x64-clang
on: [push, pull_request]
jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      env:
        CC: clang
        CXX: clang++
      run: cmake -S examples -B build -P arcbuild.cmake -DPLATFORM=linux -DARCH=x64
    - name: build
      run: cmake --build build -j2
